const userTypes = {
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_UP_START: "SIGN_UP_START",
    USER_ERROR: "USER_ERROR",
    RESET_PASSWORD_START: "RESET_PASSWORD_START",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_STATE: "RESET_STATE",
    SIGN_IN_GOOGLE_START: "SIGN_IN_GOOGLE_START",

    CHANGE_PASSWORD_START: "CHANGE_PASSWORD_START",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_EMAIL_START: "CHANGE_EMAIL_START",
    CHANGE_EMAIL_SUCCESS: "CHANGE_EMAIL_SUCCESS",
    RESET_PASSWORD_EMAIL_STATE: "RESET_PASSWORD_EMAIL_STATE",

    CHANGE_NAME_START: "CHANGE_NAME_START",
    CHANGE_NAME_SUCCESS: "CHANGE_NAME_SUCCESS",
    RESET_NAME_STATE: "RESET_NAME_STATE",

};
export default userTypes;